version: '3'
services:
  applications:
    image: tianon/true
    volumes:
     - /data/Work:/var/www
  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - /data/Work:/var/www
    tty: true
  php-fpm:
    build: ./services/php
  memcached:
    image: memcached:latest
    ports:
     - "11211:11211"
  redis:
    image: redis:latest
    ports: 
     - "6379:6379"
