version: '3.1'
services:
  nginx:
    build: ./services/nginx
    volumes:
        - /Users/yiche1/count/github.com/wubaiqing:/var/www:ro
        - /tmp:/var/log/nginx
        - ./services/nginx/sites:/etc/nginx/sites-available
    ports:
        - "8090:80"
    depends_on:
        - php-fpm
    tty: true

  php-fpm:
    build: ./services/php
    volumes:
     - /Users/yiche1/count/github.com/wubaiqing:/var/www
    depends_on:
        - mysql
        - redis

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

  redis:
    image: redis:latest
    ports: 
     - "63790:6379"

  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes: 
      - ./services/mysql/store:/var/lib/mysql
    ports:
      - "33060:3306"

