version: '3'
services:
  nginx:
    build: ./services/nginx
    volumes:
        - /data/Work:/var/www
        - /tmp:/var/log/nginx
        - ./services/nginx/sites:/etc/nginx/sites-available
    ports:
        - "80:80"
    depends_on:
        - php-fpm
    tty: true

  php-fpm:
    build: ./services/php
    volumes:
     - /data/Work:/var/www
    depends_on:
        - mysql
        - memcached
        - redis

  memcached:
    image: memcached:latest
    ports:
     - "11211:11211"

  redis:
    image: redis:latest
    ports: 
     - "6379:6379"

  mysql:
    build: ./services/mysql/
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_USER: homestead
      MYSQL_ROOT_PASSWORD: secret
    volumes:
        - ./mysql/store:/var/lib/mysql
    ports:
      - 33060:3306

